# Generated by Django 4.0.5 on 2022-06-16 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Language',
        ),
    ]
