# Generated by Django 4.0.6 on 2022-07-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_review_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, '1/10- Waste of Time'), (2, '2/20 - Horrible'), (3, '3/10 - Terrible'), (4, '4/10 - Bad'), (5, '5/10 - OK'), (6, '6/10 - Not bad'), (7, '7/10 - Good'), (8, '8/10 - Very Good'), (9, '9/10 - Excellent'), (10, '10/10 - Masterpiece')]),
        ),
    ]
